trigger:
- main

pool:
  name: 'agent1'

variables:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
  MAVEN_HOME: /opt/maven
  PATH: /usr/bin:/usr/lib/jvm/java-11-openjdk-amd64/bin:/opt/maven/bin

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Java Home: $JAVA_HOME"
      echo "Maven Home: $MAVEN_HOME"
      java -version
      mvn -version
  displayName: 'Verify Java and Maven'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-Xmx1024m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    mavenVersionOption: 'Path'
    mavenDirectory: '$(MAVEN_HOME)'
    mavenSetM2Home: false
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
